#!/usr/bin/env python3
"""Build CameraToolsPhotoreal.addon64, the ReShade add-on that relights Genshin's world inside its own frame.

The shaders compile offline to DXBC with vkd3d-compiler and are embedded in the add-on. The C++ compiles with LLVM's
clang-cl and lld-link against ReShade's API headers, which this script downloads at the ReShade version the add-on is
written for, as ReShadeBridge/build.py does. The Windows SDK and C runtime come from --sdk, a folder made by xwin. On
Windows, leave out --sdk and run from a Visual Studio developer prompt.

vkd3d-compiler comes from --vkd3d-compiler, else the PHOTOREAL_VKD3D_COMPILER environment variable, else the one the
melonloader workspace builds at .work/build/reshade/vkd3d/vkd3d-compiler when this folder is inside that workspace.
"""

import argparse
import os
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
NAME = "CameraToolsPhotoreal.addon64"
# ReShade 6.8.0, whose add-on API version 20 the add-on is built and tested against.
RESHADE_COMMIT = "18deaa52de0c425a78b329e9cb3c497281cd00ec"
RESHADE_HEADERS = [
    "reshade.hpp", "reshade_api.hpp", "reshade_api_device.hpp", "reshade_api_format.hpp", "reshade_api_pipeline.hpp",
    "reshade_api_resource.hpp", "reshade_events.hpp", "reshade_overlay.hpp",
]
SOURCES = ["addon.cpp", "gpu.cpp", "core/recipe.cpp", "core/plan.cpp", "core/png.cpp"]
# (symbol in photoreal_shaders.h, source in shaders/, profile)
SHADERS = [
    ("kFullscreenVs", "fullscreen_vs.hlsl", "vs_5_0"), ("kAoPs", "ao_ps.hlsl", "ps_5_0"), ("kAmbientPs", "ambient_ps.hlsl", "ps_5_0"),
    ("kContactPs", "contact_ps.hlsl", "ps_5_0"), ("kContactShadowsPs", "contact_shadows_ps.hlsl", "ps_5_0"), ("kViewPs", "view_ps.hlsl", "ps_5_0"),
]
WORKSPACE_VKD3D = Path(".work/build/reshade/vkd3d/vkd3d-compiler")
DEPS = HERE / ".deps"
# Where Homebrew's llvm and lld formulas put the tools, for a PATH that does not have them.
HOMEBREW = {"clang-cl": Path("/opt/homebrew/opt/llvm/bin/clang-cl"), "lld-link": Path("/opt/homebrew/bin/lld-link")}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sdk", type=Path, help="a Windows SDK and CRT made by 'xwin splat' (not needed on Windows)")
    parser.add_argument("--out-dir", type=Path, default=HERE / "bin", help=f"the folder to write {NAME} to")
    parser.add_argument("--reshade-include", type=Path, help="ReShade's include folder, instead of downloading it")
    parser.add_argument("--vkd3d-compiler", type=Path, help="vkd3d-compiler, if not in PHOTOREAL_VKD3D_COMPILER or the workspace")
    parser.add_argument("--clang-cl", type=Path, help="clang-cl, if it is not on PATH")
    parser.add_argument("--lld-link", type=Path, help="lld-link, if it is not on PATH")
    parser.add_argument("--work", type=Path, default=HERE / "obj", help="where the shaders and object files go")
    args = parser.parse_args()

    vkd3d = vkd3d_compiler(args.vkd3d_compiler)
    clang_cl = tool("clang-cl", args.clang_cl)
    lld_link = tool("lld-link", args.lld_link)
    reshade = args.reshade_include or download_headers()
    includes, libpaths = sdk_paths(args.sdk)

    args.work.mkdir(parents=True, exist_ok=True)
    embed_shaders(vkd3d, args.work)
    objects = []
    for source in SOURCES:
        obj = args.work / (Path(source).stem + ".obj")
        run(clang_cl, "--target=x86_64-pc-windows-msvc", "/c", "/std:c++17", "/MT", "/O2", "/EHsc", "/W4", "/WX",
            "/DNOMINMAX", "/DWIN32_LEAN_AND_MEAN", *[f"/imsvc{path}" for path in includes], f"/imsvc{reshade}",
            f"/I{args.work}", f"/Fo{obj}", "--", HERE / source)
        objects.append(obj)
    out = args.out_dir / NAME
    args.out_dir.mkdir(parents=True, exist_ok=True)
    run(lld_link, "/dll", "/nologo", "/MANIFEST:NO", "/OPT:REF", "/OPT:ICF", f"/out:{out}",
        f"/implib:{args.work / 'photoreal.lib'}", *[f"/libpath:{path}" for path in libpaths], *objects)
    print(f"{out}: ReShade add-on for API version {api_version(reshade)}, {out.stat().st_size} bytes")


def vkd3d_compiler(given):
    named = given or os.environ.get("PHOTOREAL_VKD3D_COMPILER")
    if named:
        if not Path(named).is_file():
            sys.exit(f"vkd3d-compiler not found at {named}.")
        return Path(named)
    for parent in HERE.parents:
        if (parent / WORKSPACE_VKD3D).exists():
            return parent / WORKSPACE_VKD3D
    sys.exit("vkd3d-compiler not found. Pass --vkd3d-compiler or set PHOTOREAL_VKD3D_COMPILER. In the melonloader "
             "workspace, tools/deck/ReShadeBuild/build_reshade.py builds it.")


# vkd3d-compiler has no include path option and resolves #include against its working directory, so it runs in shaders/.
def embed_shaders(vkd3d, work):
    lines = ["// Generated by build.py from shaders/. Do not edit.", "#pragma once", ""]
    for symbol, source, profile in SHADERS:
        dxbc = work / (Path(source).stem + ".dxbc")
        run(vkd3d.resolve(), "-x", "hlsl", "-b", "dxbc-tpf", "--profile", profile, source, "-o", dxbc.resolve(), cwd=HERE / "shaders")
        data = dxbc.read_bytes()
        rows = [", ".join(f"0x{byte:02x}" for byte in data[i:i + 24]) for i in range(0, len(data), 24)]
        lines += [f"static const unsigned char {symbol}[] = {{", *[f"    {row}," for row in rows], "};", ""]
    (work / "photoreal_shaders.h").write_text("\n".join(lines))


def tool(name, given):
    found = given or shutil.which(name) or (HOMEBREW[name] if HOMEBREW[name].exists() else None)
    if not found:
        sys.exit(f"{name} not found. Install LLVM (on macOS: brew install llvm lld), put it on PATH, or pass --{name}.")
    return Path(found)


# Only the headers the add-on includes, from the pinned commit, so no ReShade checkout is needed.
def download_headers():
    include = DEPS / f"reshade-{RESHADE_COMMIT[:12]}/include"
    include.mkdir(parents=True, exist_ok=True)
    for name in RESHADE_HEADERS:
        path = include / name
        if path.exists():
            continue
        url = f"https://raw.githubusercontent.com/crosire/reshade/{RESHADE_COMMIT}/include/{name}"
        print(f"Downloading {url}")
        with urllib.request.urlopen(url) as response:
            data = response.read()
        path.with_suffix(".part").write_bytes(data)
        path.with_suffix(".part").replace(path)
    return include


def sdk_paths(sdk):
    if sdk is None:
        if "INCLUDE" not in os.environ or "LIB" not in os.environ:
            sys.exit("No Windows SDK. Pass --sdk with a folder made by 'xwin --accept-license splat --output <folder>', "
                     "or on Windows run from a Visual Studio developer prompt.")
        return [], []
    if not (sdk / "sdk/include/um/Windows.h").exists():
        sys.exit(f"{sdk} is not an xwin SDK folder: it has no sdk/include/um/Windows.h.")
    # winrt holds wrl/client.h, for ComPtr.
    includes = [sdk / "crt/include", sdk / "sdk/include/ucrt", sdk / "sdk/include/um", sdk / "sdk/include/shared", sdk / "sdk/include/winrt"]
    # xwin names the folders x86_64, or x64 with --preserve-ms-arch-notation.
    arch = "x64" if (sdk / "crt/lib/x64").exists() else "x86_64"
    libpaths = [sdk / f"crt/lib/{arch}", sdk / f"sdk/lib/um/{arch}", sdk / f"sdk/lib/ucrt/{arch}"]
    return includes, libpaths


def api_version(include):
    for line in (include / "reshade.hpp").read_text().splitlines():
        if line.startswith("#define RESHADE_API_VERSION "):
            return line.split()[2]
    sys.exit(f"{include / 'reshade.hpp'} does not define RESHADE_API_VERSION.")


def run(*command, cwd=None):
    result = subprocess.run([str(part) for part in command], capture_output=True, text=True, cwd=cwd)
    if result.returncode != 0:
        sys.exit(f"{Path(str(command[0])).name} failed:\n{result.stdout}{result.stderr}")


if __name__ == "__main__":
    main()
