#include "gpu.h"

#include "photoreal_shaders.h"  // generated by build.py: kFullscreenVs, kAoPs, kAmbientPs, kContactPs, kContactShadowsPs, kSunPs,
                                // kSunShadowsPs, kAtmospherePs, kTonemapPs, kViewPs, kAccumulatePs, kPresentPs (DXBC)

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <utility>

namespace photoreal
{
    // Mirrors shaders/common.hlsli's cbuffer Constants : register(b0). One layout for every shader.
    struct Constants
    {
        float world_to_view[16];
        float clip_to_view[16];
        float view_to_clip[16];
        float render_size[4];
        float level, ao_strength, ao_radius, flip;
        float projection_scale;
        uint32_t decode;
        float foliage_ao_strength;
        float contact_length;
        float toward_sun[3];
        float contact_strength;
        float contact_thickness;
        uint32_t label_length;
        float contact_foliage_strength;
        float padding;
        uint32_t label[8];
        float sun_color[3];
        float atmosphere_density;
        float sky_color[3];
        float height_falloff;
        float sun_scatter;
        float anisotropy;
        float exposure_scale;
        uint32_t curve;
        float bloom_strength;
        float saturation;
        float contrast;
        float padding2;
        uint32_t sun_cascades, sun_columns, sun_rows;
        float sun_light_size;
        float sun_min_penumbra;
        float sun_strength;
        float padding3[2];
        float lens_sample[2];
        float cat_eye;
        float cat_eye_falloff;
    };
    static_assert(sizeof(Constants) == 416 && offsetof(Constants, label) == 272 && offsetof(Constants, sun_color) == 304
        && offsetof(Constants, sky_color) == 320 && offsetof(Constants, bloom_strength) == 352 && offsetof(Constants, sun_cascades) == 368
        && offsetof(Constants, lens_sample) == 400, "Constants must match common.hlsli");

    // The rows of the game's tone map constants shaders/tonemap_ps.hlsl reads, 0 to 101.
    constexpr UINT kGameTonemapBytes = 102 * 16;
    static_assert(sizeof(Constants::label) == sizeof(Label::glyphs), "the label holds one byte per glyph");

    namespace
    {
        template <class T, size_t N>
        void release(T *(&items)[N])
        {
            for (T *&item : items)
                if (item)
                {
                    item->Release();
                    item = nullptr;
                }
        }

        template <class T>
        void release(T *&item)
        {
            if (item)
            {
                item->Release();
                item = nullptr;
            }
        }

        bool is_depth(DXGI_FORMAT format)
        {
            return format == DXGI_FORMAT_D32_FLOAT_S8X24_UINT || format == DXGI_FORMAT_R32G8X24_TYPELESS;
        }

        // CopyResource only needs formats of one family, so a mirror holds the typeless one and can take any view.
        DXGI_FORMAT typeless(DXGI_FORMAT format)
        {
            switch (format)
            {
            case DXGI_FORMAT_R32G8X24_TYPELESS: case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
            case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS: case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
                return DXGI_FORMAT_R32G8X24_TYPELESS;
            case DXGI_FORMAT_R16G16B16A16_TYPELESS: case DXGI_FORMAT_R16G16B16A16_FLOAT: case DXGI_FORMAT_R16G16B16A16_UNORM:
                return DXGI_FORMAT_R16G16B16A16_TYPELESS;
            case DXGI_FORMAT_R10G10B10A2_TYPELESS: case DXGI_FORMAT_R10G10B10A2_UNORM: case DXGI_FORMAT_R10G10B10A2_UINT:
                return DXGI_FORMAT_R10G10B10A2_TYPELESS;
            case DXGI_FORMAT_R8G8B8A8_TYPELESS: case DXGI_FORMAT_R8G8B8A8_UNORM: case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
            case DXGI_FORMAT_R8G8B8A8_UINT: case DXGI_FORMAT_R8G8B8A8_SNORM: case DXGI_FORMAT_R8G8B8A8_SINT:
                return DXGI_FORMAT_R8G8B8A8_TYPELESS;
            case DXGI_FORMAT_B8G8R8A8_TYPELESS: case DXGI_FORMAT_B8G8R8A8_UNORM: case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
                return DXGI_FORMAT_B8G8R8A8_TYPELESS;
            case DXGI_FORMAT_R8G8_TYPELESS: case DXGI_FORMAT_R8G8_UNORM: case DXGI_FORMAT_R8G8_UINT:
                return DXGI_FORMAT_R8G8_TYPELESS;
            case DXGI_FORMAT_R16_TYPELESS: case DXGI_FORMAT_R16_FLOAT: case DXGI_FORMAT_D16_UNORM: case DXGI_FORMAT_R16_UNORM:
                return DXGI_FORMAT_R16_TYPELESS;
            case DXGI_FORMAT_R8_TYPELESS: case DXGI_FORMAT_R8_UNORM: case DXGI_FORMAT_R8_UINT:
                return DXGI_FORMAT_R8_TYPELESS;
            default:
                return format;
            }
        }

        // The format our views use: the game's view format without sRGB, so shaders see the stored values as they are.
        DXGI_FORMAT linear(DXGI_FORMAT format)
        {
            switch (format)
            {
            case DXGI_FORMAT_R8G8B8A8_TYPELESS: case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: return DXGI_FORMAT_R8G8B8A8_UNORM;
            case DXGI_FORMAT_B8G8R8A8_TYPELESS: case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: return DXGI_FORMAT_B8G8R8A8_UNORM;
            case DXGI_FORMAT_R10G10B10A2_TYPELESS: return DXGI_FORMAT_R10G10B10A2_UNORM;
            case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_FLOAT;
            case DXGI_FORMAT_R8G8_TYPELESS: return DXGI_FORMAT_R8G8_UNORM;
            case DXGI_FORMAT_R16_TYPELESS: case DXGI_FORMAT_D16_UNORM: return DXGI_FORMAT_R16_UNORM;
            case DXGI_FORMAT_R8_TYPELESS: return DXGI_FORMAT_R8_UNORM;
            default: return format;
            }
        }

        std::optional<PixelOrder> pixel_order(DXGI_FORMAT format)
        {
            switch (typeless(format))
            {
            case DXGI_FORMAT_R8G8B8A8_TYPELESS: return PixelOrder::rgba;
            case DXGI_FORMAT_B8G8R8A8_TYPELESS: case DXGI_FORMAT_B8G8R8X8_TYPELESS: case DXGI_FORMAT_B8G8R8X8_UNORM:
            case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB:
                return PixelOrder::bgra;
            default: return std::nullopt;
            }
        }

        ID3D11Resource *native(const Texture &texture) { return reinterpret_cast<ID3D11Resource *>(static_cast<uint64_t>(texture.id)); }

        // The constants every pass shares: the camera, the render size and flip. false when the projection does not invert.
        bool pass_constants(const Camera &camera, Size size, bool flip, Constants &out)
        {
            out = {};
            if (!invert(camera.view_to_clip, out.clip_to_view))
                return false;
            std::memcpy(out.world_to_view, camera.world_to_view, sizeof out.world_to_view);
            std::memcpy(out.view_to_clip, camera.view_to_clip, sizeof out.view_to_clip);
            std::memcpy(out.toward_sun, camera.toward_sun, sizeof out.toward_sun);
            std::memcpy(out.sun_color, camera.sun_color, sizeof out.sun_color);
            std::memcpy(out.sky_color, camera.sky_color, sizeof out.sky_color);
            out.render_size[0] = static_cast<float>(size.width);
            out.render_size[1] = static_cast<float>(size.height);
            out.render_size[2] = 1.0f / size.width;
            out.render_size[3] = 1.0f / size.height;
            out.flip = flip ? 1.0f : 0.0f;
            out.projection_scale = 0.5f * size.height * camera.view_to_clip[5];
            return true;
        }
    }

    StateGuard::StateGuard(ID3D11DeviceContext1 *context, const char *&moved) : context_(context), moved_(moved)
    {
        context_->OMGetRenderTargets(1, &tripwire_rtv_, &tripwire_dsv_);
        context_->PSGetShader(&tripwire_ps_, nullptr, nullptr);

        context_->IAGetInputLayout(&input_layout_);
        context_->IAGetPrimitiveTopology(&topology_);
        context_->VSGetShader(&vs_.shader, vs_.instances, &vs_.count);
        context_->PSGetShader(&ps_.shader, ps_.instances, &ps_.count);
        context_->GSGetShader(&gs_.shader, gs_.instances, &gs_.count);
        context_->HSGetShader(&hs_.shader, hs_.instances, &hs_.count);
        context_->DSGetShader(&ds_.shader, ds_.instances, &ds_.count);
        context_->CSGetShader(&cs_.shader, cs_.instances, &cs_.count);
        context_->VSGetShaderResources(0, kSrvSlots, vs_stage_.srvs);
        context_->PSGetShaderResources(0, kSrvSlots, ps_stage_.srvs);
        context_->CSGetShaderResources(0, kSrvSlots, cs_stage_.srvs);
        context_->VSGetSamplers(0, kSamplerSlots, vs_stage_.samplers);
        context_->PSGetSamplers(0, kSamplerSlots, ps_stage_.samplers);
        context_->CSGetSamplers(0, kSamplerSlots, cs_stage_.samplers);
        context_->VSGetConstantBuffers1(0, kCbSlots, vs_stage_.cbs, vs_stage_.cb_first, vs_stage_.cb_count);
        context_->PSGetConstantBuffers1(0, kCbSlots, ps_stage_.cbs, ps_stage_.cb_first, ps_stage_.cb_count);
        context_->CSGetConstantBuffers1(0, kCbSlots, cs_stage_.cbs, cs_stage_.cb_first, cs_stage_.cb_count);
        context_->CSGetUnorderedAccessViews(0, kUavSlots, cs_uavs_);
        context_->SOGetTargets(kSoSlots, so_targets_);
        context_->OMGetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs_, &dsv_);
        context_->RSGetViewports(&viewport_count_, viewports_);
        context_->RSGetScissorRects(&scissor_count_, scissors_);
        context_->OMGetBlendState(&blend_, blend_factor_, &sample_mask_);
        context_->OMGetDepthStencilState(&depth_stencil_, &stencil_ref_);
        context_->RSGetState(&rasterizer_);

        context_->GSSetShader(nullptr, nullptr, 0);
        context_->HSSetShader(nullptr, nullptr, 0);
        context_->DSSetShader(nullptr, nullptr, 0);
        context_->SOSetTargets(0, nullptr, nullptr);
    }

    StateGuard::~StateGuard()
    {
        context_->IASetInputLayout(input_layout_);
        context_->IASetPrimitiveTopology(topology_);
        context_->VSSetShader(vs_.shader, vs_.instances, vs_.count);
        context_->PSSetShader(ps_.shader, ps_.instances, ps_.count);
        context_->GSSetShader(gs_.shader, gs_.instances, gs_.count);
        context_->HSSetShader(hs_.shader, hs_.instances, hs_.count);
        context_->DSSetShader(ds_.shader, ds_.instances, ds_.count);
        context_->CSSetShader(cs_.shader, cs_.instances, cs_.count);
        context_->VSSetShaderResources(0, kSrvSlots, vs_stage_.srvs);
        context_->PSSetShaderResources(0, kSrvSlots, ps_stage_.srvs);
        context_->CSSetShaderResources(0, kSrvSlots, cs_stage_.srvs);
        context_->VSSetSamplers(0, kSamplerSlots, vs_stage_.samplers);
        context_->PSSetSamplers(0, kSamplerSlots, ps_stage_.samplers);
        context_->CSSetSamplers(0, kSamplerSlots, cs_stage_.samplers);
        context_->VSSetConstantBuffers1(0, kCbSlots, vs_stage_.cbs, vs_stage_.cb_first, vs_stage_.cb_count);
        context_->PSSetConstantBuffers1(0, kCbSlots, ps_stage_.cbs, ps_stage_.cb_first, ps_stage_.cb_count);
        context_->CSSetConstantBuffers1(0, kCbSlots, cs_stage_.cbs, cs_stage_.cb_first, cs_stage_.cb_count);
        // -1 keeps each UAV counter and each stream-output offset where it was.
        const UINT keep_counts[kUavSlots] = { ~0u, ~0u };
        context_->CSSetUnorderedAccessViews(0, kUavSlots, cs_uavs_, keep_counts);
        const UINT append[kSoSlots] = { ~0u, ~0u, ~0u, ~0u };
        context_->SOSetTargets(kSoSlots, so_targets_, append);
        context_->OMSetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs_, dsv_);
        context_->RSSetViewports(viewport_count_, viewports_);
        context_->RSSetScissorRects(scissor_count_, scissors_);
        context_->OMSetBlendState(blend_, blend_factor_, sample_mask_);
        context_->OMSetDepthStencilState(depth_stencil_, stencil_ref_);
        context_->RSSetState(rasterizer_);

        ID3D11RenderTargetView *rtv = nullptr;
        ID3D11DepthStencilView *dsv = nullptr;
        ID3D11PixelShader *ps = nullptr;
        context_->OMGetRenderTargets(1, &rtv, &dsv);
        context_->PSGetShader(&ps, nullptr, nullptr);
        if (rtv != tripwire_rtv_)
            moved_ = "render target 0";
        else if (dsv != tripwire_dsv_)
            moved_ = "depth-stencil view";
        else if (ps != tripwire_ps_)
            moved_ = "pixel shader";
        release(rtv);
        release(dsv);
        release(ps);

        release(tripwire_rtv_);
        release(tripwire_dsv_);
        release(tripwire_ps_);
        release(input_layout_);
        for (auto *bound : { &vs_.instances, &ps_.instances, &gs_.instances, &hs_.instances, &ds_.instances, &cs_.instances })
            release(*bound);
        release(vs_.shader);
        release(ps_.shader);
        release(gs_.shader);
        release(hs_.shader);
        release(ds_.shader);
        release(cs_.shader);
        for (Stage *stage : { &vs_stage_, &ps_stage_, &cs_stage_ })
        {
            release(stage->srvs);
            release(stage->samplers);
            release(stage->cbs);
        }
        release(cs_uavs_);
        release(so_targets_);
        release(rtvs_);
        release(dsv_);
        release(blend_);
        release(depth_stencil_);
        release(rasterizer_);
    }

    bool Mirror::sync(ID3D11Device *device, ID3D11Resource *like, DXGI_FORMAT view_format, bool render_target)
    {
        ComPtr<ID3D11Texture2D> game;
        if (FAILED(like->QueryInterface(IID_PPV_ARGS(game.GetAddressOf()))))
            return false;
        D3D11_TEXTURE2D_DESC desc;
        game->GetDesc(&desc);
        if (desc.SampleDesc.Count != 1 || desc.ArraySize != 1)
            return false;
        desc.Format = typeless(desc.Format);
        desc.Usage = D3D11_USAGE_DEFAULT;
        desc.BindFlags = D3D11_BIND_SHADER_RESOURCE | (render_target ? D3D11_BIND_RENDER_TARGET : 0);
        desc.CPUAccessFlags = 0;
        desc.MiscFlags = 0;
        if (texture_ && view_format == view_format_ && std::memcmp(&desc, &desc_, sizeof desc) == 0)
            return true;

        *this = Mirror {};
        if (FAILED(device->CreateTexture2D(&desc, nullptr, &texture_)))
            return false;
        D3D11_SHADER_RESOURCE_VIEW_DESC srv = {};
        srv.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
        srv.Texture2D.MipLevels = 1;
        if (is_depth(view_format))
        {
            srv.Format = DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;
            if (FAILED(device->CreateShaderResourceView(texture_.Get(), &srv, &srv_)))
                return *this = Mirror {}, false;
            srv.Format = DXGI_FORMAT_X32_TYPELESS_G8X24_UINT;
            if (FAILED(device->CreateShaderResourceView(texture_.Get(), &srv, &stencil_srv_)))
                return *this = Mirror {}, false;
        }
        else
        {
            srv.Format = linear(view_format);
            if (FAILED(device->CreateShaderResourceView(texture_.Get(), &srv, &srv_)))
                return *this = Mirror {}, false;
            D3D11_RENDER_TARGET_VIEW_DESC rtv = {};
            rtv.Format = srv.Format;
            rtv.ViewDimension = D3D11_RTV_DIMENSION_TEXTURE2D;
            if (render_target && FAILED(device->CreateRenderTargetView(texture_.Get(), &rtv, &rtv_)))
                return *this = Mirror {}, false;
        }
        desc_ = desc;
        view_format_ = view_format;
        return true;
    }

    bool Scratch::sync(ID3D11Device *device, Size size, DXGI_FORMAT format)
    {
        if (texture_ && size == size_ && format == format_)
            return true;
        *this = Scratch {};
        D3D11_TEXTURE2D_DESC desc = {};
        desc.Width = size.width;
        desc.Height = size.height;
        desc.MipLevels = 1;
        desc.ArraySize = 1;
        desc.Format = format;
        desc.SampleDesc.Count = 1;
        desc.Usage = D3D11_USAGE_DEFAULT;
        desc.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET;
        if (FAILED(device->CreateTexture2D(&desc, nullptr, &texture_)) || FAILED(device->CreateShaderResourceView(texture_.Get(), nullptr, &srv_))
            || FAILED(device->CreateRenderTargetView(texture_.Get(), nullptr, &rtv_)))
            return *this = Scratch {}, false;
        size_ = size;
        format_ = format;
        return true;
    }

    bool Staging::copy_from(ID3D11Device *device, ID3D11DeviceContext *context, ID3D11Resource *back_buffer)
    {
        ComPtr<ID3D11Texture2D> game;
        if (FAILED(back_buffer->QueryInterface(IID_PPV_ARGS(game.GetAddressOf()))))
            return false;
        D3D11_TEXTURE2D_DESC desc;
        game->GetDesc(&desc);
        const std::optional<PixelOrder> order = pixel_order(desc.Format);
        if (!order || desc.SampleDesc.Count != 1)
            return false;
        desc.MipLevels = 1;
        desc.ArraySize = 1;
        desc.Usage = D3D11_USAGE_STAGING;
        desc.BindFlags = 0;
        desc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
        desc.MiscFlags = 0;
        if (!texture_ || std::memcmp(&desc, &desc_, sizeof desc) != 0)
        {
            *this = Staging {};
            if (FAILED(device->CreateTexture2D(&desc, nullptr, &texture_)))
                return false;
            desc_ = desc;
            order_ = *order;
        }
        context->CopySubresourceRegion(texture_.Get(), 0, 0, 0, 0, back_buffer, 0, nullptr);
        return true;
    }

    std::optional<RawFrame> Staging::read(ID3D11DeviceContext *context) const
    {
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (!texture_ || FAILED(context->Map(texture_.Get(), 0, D3D11_MAP_READ, 0, &mapped)))
            return std::nullopt;
        RawFrame frame { { desc_.Width, desc_.Height }, order_, std::vector<uint8_t>(size_t(desc_.Width) * desc_.Height * 4) };
        const size_t row = size_t(desc_.Width) * 4;
        for (UINT y = 0; y < desc_.Height; y++)
            std::memcpy(&frame.bytes[y * row], static_cast<const uint8_t *>(mapped.pData) + size_t(y) * mapped.RowPitch, row);
        context->Unmap(texture_.Get(), 0);
        return frame;
    }

    bool Gpu::init(ID3D11Device *device, ID3D11DeviceContext *context)
    {
        ComPtr<ID3D11DeviceContext1> context1;
        if (FAILED(context->QueryInterface(IID_PPV_ARGS(context1.GetAddressOf()))))
            return false;

        D3D11_SAMPLER_DESC sampler = {};
        sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT;
        sampler.AddressU = sampler.AddressV = sampler.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampler.MaxLOD = D3D11_FLOAT32_MAX;
        D3D11_SAMPLER_DESC linear_sampler = sampler;
        linear_sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        // Reversed depth: the atlas stores larger values nearer the sun, so a receiver is lit where it is at least as near.
        D3D11_SAMPLER_DESC compare_sampler = sampler;
        compare_sampler.Filter = D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
        compare_sampler.ComparisonFunc = D3D11_COMPARISON_GREATER_EQUAL;

        D3D11_BUFFER_DESC buffer = {};
        buffer.ByteWidth = sizeof(Constants);
        buffer.Usage = D3D11_USAGE_DYNAMIC;
        buffer.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        buffer.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        D3D11_BUFFER_DESC game_tonemap = {};
        game_tonemap.ByteWidth = kGameTonemapBytes;
        game_tonemap.Usage = D3D11_USAGE_DEFAULT;
        game_tonemap.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        D3D11_BUFFER_DESC sun_stage = {};
        sun_stage.ByteWidth = kSunCbufferTotal;
        sun_stage.Usage = D3D11_USAGE_STAGING;
        sun_stage.CPUAccessFlags = D3D11_CPU_ACCESS_READ;

        D3D11_BLEND_DESC blend = {};
        blend.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
        D3D11_BLEND_DESC additive = blend;
        D3D11_RENDER_TARGET_BLEND_DESC &add = additive.RenderTarget[0];
        add.BlendEnable = TRUE;
        add.SrcBlend = add.DestBlend = add.SrcBlendAlpha = add.DestBlendAlpha = D3D11_BLEND_ONE;
        add.BlendOp = add.BlendOpAlpha = D3D11_BLEND_OP_ADD;
        D3D11_TEXTURE2D_DESC depth_texel = {};
        depth_texel.Width = depth_texel.Height = depth_texel.MipLevels = depth_texel.ArraySize = 1;
        depth_texel.Format = DXGI_FORMAT_R32G8X24_TYPELESS;
        depth_texel.SampleDesc.Count = 1;
        depth_texel.Usage = D3D11_USAGE_STAGING;
        depth_texel.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
        D3D11_DEPTH_STENCIL_DESC depth = {};
        D3D11_RASTERIZER_DESC rasterizer = {};
        rasterizer.FillMode = D3D11_FILL_SOLID;
        rasterizer.CullMode = D3D11_CULL_NONE;
        rasterizer.DepthClipEnable = TRUE;

        Gpu made;
        const bool ok = SUCCEEDED(device->CreateVertexShader(kFullscreenVs, sizeof kFullscreenVs, nullptr, &made.fullscreen_vs_))
            && SUCCEEDED(device->CreatePixelShader(kAoPs, sizeof kAoPs, nullptr, &made.ao_ps_))
            && SUCCEEDED(device->CreatePixelShader(kAmbientPs, sizeof kAmbientPs, nullptr, &made.ambient_ps_))
            && SUCCEEDED(device->CreatePixelShader(kContactPs, sizeof kContactPs, nullptr, &made.contact_ps_))
            && SUCCEEDED(device->CreatePixelShader(kContactShadowsPs, sizeof kContactShadowsPs, nullptr, &made.contact_shadows_ps_))
            && SUCCEEDED(device->CreatePixelShader(kSunPs, sizeof kSunPs, nullptr, &made.sun_ps_))
            && SUCCEEDED(device->CreatePixelShader(kSunShadowsPs, sizeof kSunShadowsPs, nullptr, &made.sun_shadows_ps_))
            && SUCCEEDED(device->CreatePixelShader(kAtmospherePs, sizeof kAtmospherePs, nullptr, &made.atmosphere_ps_))
            && SUCCEEDED(device->CreatePixelShader(kTonemapPs, sizeof kTonemapPs, nullptr, &made.tonemap_ps_))
            && SUCCEEDED(device->CreatePixelShader(kViewPs, sizeof kViewPs, nullptr, &made.view_ps_))
            && SUCCEEDED(device->CreatePixelShader(kAccumulatePs, sizeof kAccumulatePs, nullptr, &made.accumulate_ps_))
            && SUCCEEDED(device->CreatePixelShader(kPresentPs, sizeof kPresentPs, nullptr, &made.present_ps_))
            && SUCCEEDED(device->CreateSamplerState(&sampler, &made.point_))
            && SUCCEEDED(device->CreateSamplerState(&linear_sampler, &made.linear_))
            && SUCCEEDED(device->CreateSamplerState(&compare_sampler, &made.lit_compare_))
            && SUCCEEDED(device->CreateBuffer(&buffer, nullptr, &made.constants_))
            && SUCCEEDED(device->CreateBuffer(&game_tonemap, nullptr, &made.game_tonemap_))
            && SUCCEEDED(device->CreateBlendState(&blend, &made.opaque_))
            && SUCCEEDED(device->CreateBlendState(&additive, &made.additive_))
            && SUCCEEDED(device->CreateTexture2D(&depth_texel, nullptr, &made.depth_texel_))
            && SUCCEEDED(device->CreateDepthStencilState(&depth, &made.no_depth_))
            && SUCCEEDED(device->CreateRasterizerState(&rasterizer, &made.no_cull_));
        if (!ok)
            return false;
        for (size_t i = 0; i < kSunCbufferBytes.size(); i++)
        {
            D3D11_BUFFER_DESC game_sun = game_tonemap;
            game_sun.ByteWidth = kSunCbufferBytes[i];
            if (FAILED(device->CreateBuffer(&game_sun, nullptr, &made.game_sun_[i])))
                return false;
        }
        for (SunStage &stage : made.sun_stages_)
            if (FAILED(device->CreateBuffer(&sun_stage, nullptr, &stage.buffer)))
                return false;
        made.device_ = device;
        made.context_ = context1;
        *this = std::move(made);
        return true;
    }

    void Gpu::upload(const Constants &constants)
    {
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (FAILED(context_->Map(constants_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
            return;
        std::memcpy(mapped.pData, &constants, sizeof constants);
        context_->Unmap(constants_.Get(), 0);
    }

    void Gpu::draw_fullscreen(ID3D11PixelShader *shader, ID3D11ShaderResourceView *const *srvs, UINT srv_count, ID3D11RenderTargetView *target, Size size,
        ID3D11BlendState *blend)
    {
        ID3D11DeviceContext1 *c = context_.Get();
        ID3D11SamplerState *const samplers[kSamplerSlots] = { point_.Get(), linear_.Get(), lit_compare_.Get() };
        ID3D11Buffer *const buffers[1] = { constants_.Get() };
        const D3D11_VIEWPORT viewport = { 0, 0, static_cast<float>(size.width), static_cast<float>(size.height), 0, 1 };
        c->IASetInputLayout(nullptr);
        c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        c->VSSetShader(fullscreen_vs_.Get(), nullptr, 0);
        c->PSSetShader(shader, nullptr, 0);
        c->PSSetConstantBuffers(0, 1, buffers);
        c->PSSetSamplers(0, kSamplerSlots, samplers);
        c->OMSetRenderTargets(1, &target, nullptr);
        c->PSSetShaderResources(0, srv_count, srvs);
        c->RSSetViewports(1, &viewport);
        c->RSSetState(no_cull_.Get());
        c->OMSetBlendState(blend ? blend : opaque_.Get(), nullptr, 0xFFFFFFFF);
        c->OMSetDepthStencilState(no_depth_.Get(), 0);
        c->Draw(3, 0);
    }

    bool Gpu::mirror_gbuffer(const FrameMap &map, Scratch &scratch)
    {
        const Texture &normals = *map[Entry::normals], &depth = *map[Entry::depth];
        ID3D11Device *d = device_.Get();
        if (!normals_.sync(d, native(normals), static_cast<DXGI_FORMAT>(normals.format), false)
            || !depth_.sync(d, native(depth), static_cast<DXGI_FORMAT>(depth.format), false) || !scratch.sync(d, map.render, DXGI_FORMAT_R8_UNORM))
            return false;
        normals_.copy_from(context_.Get(), native(normals));
        depth_.copy_from(context_.Get(), native(depth));
        return true;
    }

    std::optional<GameCall> Gpu::run_ambient(const FrameMap &map, const AmbientSettings &settings, const Camera &camera, bool flip)
    {
        const Texture &irradiance = *map[Entry::ambient_diffuse];
        const auto irradiance_format = static_cast<DXGI_FORMAT>(irradiance.format);
        Constants constants;
        if (!irradiance_in_.sync(device_.Get(), native(irradiance), irradiance_format, false)
            || !irradiance_out_.sync(device_.Get(), native(irradiance), irradiance_format, true) || !pass_constants(camera, map.render, flip, constants)
            || !mirror_gbuffer(map, ao_))
            return std::nullopt;
        constants.level = settings.level;
        constants.ao_strength = settings.ao_strength;
        constants.ao_radius = settings.ao_radius;
        constants.foliage_ao_strength = settings.foliage_ao_strength;
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        irradiance_in_.copy_from(c, native(irradiance));
        // The second draw's target change unbinds ao_ as a target before it is bound at t4.
        ID3D11ShaderResourceView *const srvs[] = { irradiance_in_.srv(), normals_.srv(), depth_.srv(), depth_.stencil_srv(), ao_.srv() };
        draw_fullscreen(ao_ps_.Get(), srvs, 4, ao_.rtv(), map.render);
        draw_fullscreen(ambient_ps_.Get(), srvs, 5, irradiance_out_.rtv(), map.render);
        irradiance_out_.copy_to(c, native(irradiance));
        return GameCall::keep;
    }

    bool Gpu::gather_sun(const Texture &atlas, uint64_t frame)
    {
        sun_ready_ = false;
        ID3D11Buffer *game[4] = {};
        UINT first[4] = {}, count[4] = {};
        context_->PSGetConstantBuffers1(0, 4, game, first, count);
        bool matched = true;
        for (UINT i = 0; i < 4; i++)
        {
            if (game[i] == nullptr)
            {
                matched = false;
                continue;
            }
            D3D11_BUFFER_DESC desc;
            game[i]->GetDesc(&desc);
            // Measured as the census measures a binding: its range, or the whole buffer when bound without one.
            const UINT offset = first[i] * 16;
            const UINT bound = offset < desc.ByteWidth ? std::min(count[i] != 0 ? count[i] * 16 : desc.ByteWidth, desc.ByteWidth - offset) : 0;
            matched &= bound == kSunCbufferBytes[i];
        }
        if (matched)
        {
            ID3D11DeviceContext1 *c = context_.Get();
            SunStage &stage = sun_stages_[frame % sun_stages_.size()];
            UINT at = 0;
            for (UINT i = 0; i < 4; i++)
            {
                const D3D11_BOX box = { first[i] * 16, 0, 0, first[i] * 16 + kSunCbufferBytes[i], 1, 1 };
                c->CopySubresourceRegion(game_sun_[i].Get(), 0, 0, 0, 0, game[i], 0, &box);
                c->CopySubresourceRegion(stage.buffer.Get(), 0, at, 0, 0, game[i], 0, &box);
                at += kSunCbufferBytes[i];
            }
            stage.frame = frame;
            stage.pending = true;
            if (sun_atlas_.sync(device_.Get(), native(atlas), static_cast<DXGI_FORMAT>(atlas.format), false))
            {
                sun_atlas_.copy_from(c, native(atlas));
                sun_ready_ = true;
            }
        }
        release(game);
        return matched;
    }

    std::optional<SunCbuffers> Gpu::sun_constants(uint64_t frame)
    {
        for (uint64_t back = 1; back <= 2 && back <= frame; back++)
        {
            SunStage &stage = sun_stages_[(frame - back) % sun_stages_.size()];
            if (!stage.pending || stage.frame != frame - back)
                continue;
            D3D11_MAPPED_SUBRESOURCE mapped;
            if (FAILED(context_->Map(stage.buffer.Get(), 0, D3D11_MAP_READ, D3D11_MAP_FLAG_DO_NOT_WAIT, &mapped)))
                continue;
            SunCbuffers bytes;
            std::memcpy(bytes.data(), mapped.pData, bytes.size());
            context_->Unmap(stage.buffer.Get(), 0);
            for (SunStage &older : sun_stages_)
                if (older.frame <= stage.frame)
                    older.pending = false;
            return bytes;
        }
        return std::nullopt;
    }

    std::optional<GameCall> Gpu::run_sun_shadows(const FrameMap &map, const SunShadowSettings &settings, const Camera &camera,
        const SunShadowConstants &sun, bool flip)
    {
        const Texture &mask = *map[Entry::shadow_mask];
        const auto mask_format = static_cast<DXGI_FORMAT>(mask.format);
        Constants constants;
        if (!sun_ready_ || !shadow_mask_in_.sync(device_.Get(), native(mask), mask_format, false)
            || !shadow_mask_out_.sync(device_.Get(), native(mask), mask_format, true) || !pass_constants(camera, map.render, flip, constants)
            || !mirror_gbuffer(map, sun_))
            return std::nullopt;
        constants.sun_cascades = sun.cascades;
        constants.sun_columns = sun.columns;
        constants.sun_rows = sun.rows;
        constants.sun_light_size = settings.light_size;
        constants.sun_min_penumbra = settings.min_penumbra;
        constants.sun_strength = settings.strength;
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        shadow_mask_in_.copy_from(c, native(mask));
        ID3D11Buffer *const game[] = { game_sun_[0].Get(), game_sun_[1].Get(), game_sun_[2].Get(), game_sun_[3].Get() };
        c->PSSetConstantBuffers(1, 4, game);
        // The second draw's target change unbinds sun_ as a target before it is bound at t4.
        ID3D11ShaderResourceView *const raw[] = { shadow_mask_in_.srv(), normals_.srv(), depth_.srv(), depth_.stencil_srv(), nullptr, sun_atlas_.srv() };
        draw_fullscreen(sun_ps_.Get(), raw, 6, sun_.rtv(), map.render);
        ID3D11ShaderResourceView *const blur[] = { shadow_mask_in_.srv(), normals_.srv(), depth_.srv(), depth_.stencil_srv(), sun_.srv() };
        draw_fullscreen(sun_shadows_ps_.Get(), blur, 5, shadow_mask_out_.rtv(), map.render);
        shadow_mask_out_.copy_to(c, native(mask));
        return GameCall::keep;
    }

    std::optional<GameCall> Gpu::run_contact_shadows(const FrameMap &map, const ContactShadowSettings &settings, const Camera &camera, bool flip)
    {
        const Texture &mask = *map[Entry::shadow_mask];
        const auto mask_format = static_cast<DXGI_FORMAT>(mask.format);
        Constants constants;
        if (!shadow_mask_in_.sync(device_.Get(), native(mask), mask_format, false)
            || !shadow_mask_out_.sync(device_.Get(), native(mask), mask_format, true) || !pass_constants(camera, map.render, flip, constants)
            || !mirror_gbuffer(map, contact_))
            return std::nullopt;
        constants.contact_length = settings.length;
        constants.contact_strength = settings.strength;
        constants.contact_thickness = settings.thickness;
        constants.contact_foliage_strength = settings.foliage_strength;
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        shadow_mask_in_.copy_from(c, native(mask));
        // The second draw's target change unbinds contact_ as a target before it is bound at t4.
        ID3D11ShaderResourceView *const srvs[] = { shadow_mask_in_.srv(), normals_.srv(), depth_.srv(), depth_.stencil_srv(), contact_.srv() };
        draw_fullscreen(contact_ps_.Get(), srvs, 4, contact_.rtv(), map.render);
        draw_fullscreen(contact_shadows_ps_.Get(), srvs, 5, shadow_mask_out_.rtv(), map.render);
        shadow_mask_out_.copy_to(c, native(mask));
        return GameCall::keep;
    }

    std::optional<GameCall> Gpu::run_atmosphere(const FrameMap &map, const AtmosphereSettings &settings, const Camera &camera, bool flip)
    {
        const Texture &scene = *map[Entry::hdr_scene], &depth = *map[Entry::depth];
        const auto scene_format = static_cast<DXGI_FORMAT>(scene.format);
        ID3D11Device *d = device_.Get();
        Constants constants;
        if (!scene_in_.sync(d, native(scene), scene_format, false) || !scene_out_.sync(d, native(scene), scene_format, true)
            || !depth_.sync(d, native(depth), static_cast<DXGI_FORMAT>(depth.format), false) || !pass_constants(camera, map.render, flip, constants))
            return std::nullopt;
        constants.atmosphere_density = settings.density;
        constants.height_falloff = settings.height_falloff;
        constants.sun_scatter = settings.sun_scatter;
        constants.anisotropy = settings.anisotropy;
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        scene_in_.copy_from(c, native(scene));
        depth_.copy_from(c, native(depth));
        ID3D11ShaderResourceView *const srvs[] = { scene_in_.srv(), nullptr, depth_.srv() };
        draw_fullscreen(atmosphere_ps_.Get(), srvs, 3, scene_out_.rtv(), map.render);
        scene_out_.copy_to(c, native(scene));
        return GameCall::keep;
    }

    bool Gpu::copy_game_tonemap_constants()
    {
        ComPtr<ID3D11Buffer> game;
        UINT first = 0, count = 0;
        context_->PSGetConstantBuffers1(0, 1, game.GetAddressOf(), &first, &count);
        if (!game || count * 16 < kGameTonemapBytes)
            return false;
        D3D11_BUFFER_DESC desc;
        game->GetDesc(&desc);
        const UINT offset = first * 16;
        if (desc.ByteWidth < offset + kGameTonemapBytes)
            return false;
        const D3D11_BOX box = { offset, 0, 0, offset + kGameTonemapBytes, 1, 1 };
        context_->CopySubresourceRegion(game_tonemap_.Get(), 0, 0, 0, 0, game.Get(), 0, &box);
        return true;
    }

    std::optional<GameCall> Gpu::run_tonemap(const FrameMap &map, const TonemapSettings &settings)
    {
        const Texture &scene = *map[Entry::hdr_scene], &out = *map[Entry::tonemap_out];
        const std::optional<Texture> &bloom = map[Entry::bloom_final];
        const auto scene_format = static_cast<DXGI_FORMAT>(scene.format);
        ID3D11Device *d = device_.Get();
        if (!scene_in_.sync(d, native(scene), scene_format, false) || !tonemap_out_.sync(d, native(out), static_cast<DXGI_FORMAT>(out.format), true)
            || (bloom && !bloom_in_.sync(d, native(*bloom), static_cast<DXGI_FORMAT>(bloom->format), false)))
            return std::nullopt;
        // Read before anything of ours is bound: the game's tone map draw still has its constants at b0.
        const bool game_constants = copy_game_tonemap_constants();
        Constants constants = {};
        constants.render_size[0] = static_cast<float>(map.render.width);
        constants.render_size[1] = static_cast<float>(map.render.height);
        constants.render_size[2] = 1.0f / map.render.width;
        constants.render_size[3] = 1.0f / map.render.height;
        constants.exposure_scale = std::exp2(settings.exposure_ev);
        constants.curve = static_cast<uint32_t>(settings.curve);
        constants.bloom_strength = settings.bloom_strength;
        constants.saturation = settings.saturation;
        constants.contrast = settings.contrast;
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        scene_in_.copy_from(c, native(scene));
        if (bloom)
            bloom_in_.copy_from(c, native(*bloom));
        ID3D11Buffer *const grade = game_constants ? game_tonemap_.Get() : nullptr;
        c->PSSetConstantBuffers(1, 1, &grade);
        ID3D11ShaderResourceView *const srvs[] = { scene_in_.srv(), bloom ? bloom_in_.srv() : nullptr };
        draw_fullscreen(tonemap_ps_.Get(), srvs, 2, tonemap_out_.rtv(), map.render);
        tonemap_out_.copy_to(c, native(out));
        return GameCall::skip;
    }

    std::optional<GameCall> Gpu::run_accumulate(const FrameMap &map, const AccumulateTick &tick, const AccumulateSettings &settings,
        const LensSample &lens, bool flip)
    {
        const Texture &scene = *map[Entry::hdr_scene];
        const auto scene_format = static_cast<DXGI_FORMAT>(scene.format);
        ID3D11Device *d = device_.Get();
        if (!scene_in_.sync(d, native(scene), scene_format, false) || (tick.present && !scene_out_.sync(d, native(scene), scene_format, true))
            || !sum_.sync(d, map.render, DXGI_FORMAT_R32G32B32A32_FLOAT))
            return std::nullopt;
        Constants constants = {};
        constants.render_size[0] = static_cast<float>(map.render.width);
        constants.render_size[1] = static_cast<float>(map.render.height);
        constants.render_size[2] = 1.0f / map.render.width;
        constants.render_size[3] = 1.0f / map.render.height;
        constants.flip = flip ? 1.0f : 0.0f;
        constants.lens_sample[0] = lens.x;
        constants.lens_sample[1] = lens.y;
        constants.cat_eye = settings.cat_eye;
        constants.cat_eye_falloff = settings.cat_eye_falloff;
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        if (tick.clear)
        {
            const FLOAT zero[4] = {};
            c->ClearRenderTargetView(sum_.rtv(), zero);
        }
        if (tick.add)
        {
            scene_in_.copy_from(c, native(scene));
            ID3D11ShaderResourceView *const srvs[] = { scene_in_.srv() };
            draw_fullscreen(accumulate_ps_.Get(), srvs, 1, sum_.rtv(), map.render, additive_.Get());
        }
        if (tick.present)
        {
            scene_in_.copy_from(c, native(scene));
            ID3D11ShaderResourceView *const srvs[] = { sum_.srv(), scene_in_.srv() };
            draw_fullscreen(present_ps_.Get(), srvs, 2, scene_out_.rtv(), map.render);
            scene_out_.copy_to(c, native(scene));
        }
        return GameCall::keep;
    }

    bool Gpu::copy_depth_texel(const FrameMap &map, Pixel at)
    {
        const Texture &depth = *map[Entry::depth];
        if (depth_texel_pending_ || !depth_.sync(device_.Get(), native(depth), static_cast<DXGI_FORMAT>(depth.format), false))
            return false;
        depth_.copy_from(context_.Get(), native(depth));
        depth_.copy_texel_to(context_.Get(), depth_texel_.Get(), at);
        depth_texel_pending_ = true;
        return true;
    }

    std::optional<float> Gpu::read_depth_texel()
    {
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (!depth_texel_pending_ || FAILED(context_->Map(depth_texel_.Get(), 0, D3D11_MAP_READ, D3D11_MAP_FLAG_DO_NOT_WAIT, &mapped)))
            return std::nullopt;
        float depth;
        std::memcpy(&depth, mapped.pData, sizeof depth);
        context_->Unmap(depth_texel_.Get(), 0);
        depth_texel_pending_ = false;
        return depth;
    }

    void Gpu::end_frame(View next_view)
    {
        std::swap(pending_, shown_);
        pending_.view = next_view;
        pending_.found = false;
        sun_ready_ = false;
    }

    bool Gpu::snapshot(const Texture &entry)
    {
        if (!pending_.image.sync(device_.Get(), native(entry), static_cast<DXGI_FORMAT>(entry.format), false))
            return false;
        pending_.image.copy_from(context_.Get(), native(entry));
        pending_.found = true;
        return true;
    }

    const char *Gpu::composite(ID3D11Resource *back_buffer, bool flip)
    {
        const char *moved = nullptr;
        if (shown_.view == View::off)
            return moved;
        ComPtr<ID3D11Texture2D> texture;
        if (FAILED(back_buffer->QueryInterface(IID_PPV_ARGS(texture.GetAddressOf()))))
            return moved;
        D3D11_TEXTURE2D_DESC desc;
        texture->GetDesc(&desc);
        if (!back_buffer_.sync(device_.Get(), back_buffer, desc.Format, true))
            return moved;

        Constants constants = {};
        constants.render_size[0] = static_cast<float>(desc.Width);
        constants.render_size[1] = static_cast<float>(desc.Height);
        constants.render_size[2] = 1.0f / desc.Width;
        constants.render_size[3] = 1.0f / desc.Height;
        constants.flip = flip ? 1.0f : 0.0f;
        constants.decode = static_cast<uint32_t>(shown_.found ? kViews[static_cast<size_t>(shown_.view)].decode : Decode::missing);
        const Label label = view_label(shown_.view, shown_.found);
        constants.label_length = label.length;
        std::memcpy(constants.label, label.glyphs.data(), sizeof constants.label);
        upload(constants);
        {
            StateGuard guard(context_.Get(), moved);
            ID3D11ShaderResourceView *const srvs[] = { shown_.found ? shown_.image.srv() : nullptr, shown_.found ? shown_.image.stencil_srv() : nullptr };
            draw_fullscreen(view_ps_.Get(), srvs, 2, back_buffer_.rtv(), back_buffer_.size());
        }
        back_buffer_.copy_to(context_.Get(), back_buffer);
        return moved;
    }
}
