#include "gpu.h"

#include "photoreal_shaders.h"  // generated by build.py: kFullscreenVs, kAmbientPs, kViewPs (DXBC)

#include <cstring>
#include <utility>

namespace photoreal
{
    // Mirrors shaders/common.hlsli's cbuffer Constants : register(b0). One layout for every shader.
    struct Constants
    {
        float world_to_view[16];
        float clip_to_view[16];
        float render_size[4];
        float level, ao_strength, ao_radius, flip;
        float projection_scale;
        uint32_t decode;
        float padding[2];
    };
    static_assert(sizeof(Constants) == 176, "Constants must match common.hlsli");

    namespace
    {
        template <class T, size_t N>
        void release(T *(&items)[N])
        {
            for (T *&item : items)
                if (item)
                {
                    item->Release();
                    item = nullptr;
                }
        }

        template <class T>
        void release(T *&item)
        {
            if (item)
            {
                item->Release();
                item = nullptr;
            }
        }

        bool is_depth(DXGI_FORMAT format)
        {
            return format == DXGI_FORMAT_D32_FLOAT_S8X24_UINT || format == DXGI_FORMAT_R32G8X24_TYPELESS;
        }

        // CopyResource only needs formats of one family, so a mirror holds the typeless one and can take any view.
        DXGI_FORMAT typeless(DXGI_FORMAT format)
        {
            switch (format)
            {
            case DXGI_FORMAT_R32G8X24_TYPELESS: case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
            case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS: case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
                return DXGI_FORMAT_R32G8X24_TYPELESS;
            case DXGI_FORMAT_R16G16B16A16_TYPELESS: case DXGI_FORMAT_R16G16B16A16_FLOAT: case DXGI_FORMAT_R16G16B16A16_UNORM:
                return DXGI_FORMAT_R16G16B16A16_TYPELESS;
            case DXGI_FORMAT_R10G10B10A2_TYPELESS: case DXGI_FORMAT_R10G10B10A2_UNORM: case DXGI_FORMAT_R10G10B10A2_UINT:
                return DXGI_FORMAT_R10G10B10A2_TYPELESS;
            case DXGI_FORMAT_R8G8B8A8_TYPELESS: case DXGI_FORMAT_R8G8B8A8_UNORM: case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
            case DXGI_FORMAT_R8G8B8A8_UINT: case DXGI_FORMAT_R8G8B8A8_SNORM: case DXGI_FORMAT_R8G8B8A8_SINT:
                return DXGI_FORMAT_R8G8B8A8_TYPELESS;
            case DXGI_FORMAT_B8G8R8A8_TYPELESS: case DXGI_FORMAT_B8G8R8A8_UNORM: case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
                return DXGI_FORMAT_B8G8R8A8_TYPELESS;
            case DXGI_FORMAT_R8G8_TYPELESS: case DXGI_FORMAT_R8G8_UNORM: case DXGI_FORMAT_R8G8_UINT:
                return DXGI_FORMAT_R8G8_TYPELESS;
            case DXGI_FORMAT_R16_TYPELESS: case DXGI_FORMAT_R16_FLOAT: case DXGI_FORMAT_D16_UNORM: case DXGI_FORMAT_R16_UNORM:
                return DXGI_FORMAT_R16_TYPELESS;
            case DXGI_FORMAT_R8_TYPELESS: case DXGI_FORMAT_R8_UNORM: case DXGI_FORMAT_R8_UINT:
                return DXGI_FORMAT_R8_TYPELESS;
            default:
                return format;
            }
        }

        // The format our views use: the game's view format without sRGB, so shaders see the stored values as they are.
        DXGI_FORMAT linear(DXGI_FORMAT format)
        {
            switch (format)
            {
            case DXGI_FORMAT_R8G8B8A8_TYPELESS: case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: return DXGI_FORMAT_R8G8B8A8_UNORM;
            case DXGI_FORMAT_B8G8R8A8_TYPELESS: case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: return DXGI_FORMAT_B8G8R8A8_UNORM;
            case DXGI_FORMAT_R10G10B10A2_TYPELESS: return DXGI_FORMAT_R10G10B10A2_UNORM;
            case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_FLOAT;
            case DXGI_FORMAT_R8G8_TYPELESS: return DXGI_FORMAT_R8G8_UNORM;
            case DXGI_FORMAT_R16_TYPELESS: case DXGI_FORMAT_D16_UNORM: return DXGI_FORMAT_R16_UNORM;
            case DXGI_FORMAT_R8_TYPELESS: return DXGI_FORMAT_R8_UNORM;
            default: return format;
            }
        }

        ID3D11Resource *native(const Texture &texture) { return reinterpret_cast<ID3D11Resource *>(static_cast<uint64_t>(texture.id)); }
    }

    StateGuard::StateGuard(ID3D11DeviceContext1 *context, const char *&moved) : context_(context), moved_(moved)
    {
        context_->OMGetRenderTargets(1, &tripwire_rtv_, &tripwire_dsv_);
        context_->PSGetShader(&tripwire_ps_, nullptr, nullptr);

        context_->IAGetInputLayout(&input_layout_);
        context_->IAGetPrimitiveTopology(&topology_);
        context_->VSGetShader(&vs_.shader, vs_.instances, &vs_.count);
        context_->PSGetShader(&ps_.shader, ps_.instances, &ps_.count);
        context_->GSGetShader(&gs_.shader, gs_.instances, &gs_.count);
        context_->HSGetShader(&hs_.shader, hs_.instances, &hs_.count);
        context_->DSGetShader(&ds_.shader, ds_.instances, &ds_.count);
        context_->CSGetShader(&cs_.shader, cs_.instances, &cs_.count);
        context_->VSGetShaderResources(0, kSrvSlots, vs_stage_.srvs);
        context_->PSGetShaderResources(0, kSrvSlots, ps_stage_.srvs);
        context_->CSGetShaderResources(0, kSrvSlots, cs_stage_.srvs);
        context_->VSGetSamplers(0, kSamplerSlots, vs_stage_.samplers);
        context_->PSGetSamplers(0, kSamplerSlots, ps_stage_.samplers);
        context_->CSGetSamplers(0, kSamplerSlots, cs_stage_.samplers);
        context_->VSGetConstantBuffers1(0, kCbSlots, vs_stage_.cbs, vs_stage_.cb_first, vs_stage_.cb_count);
        context_->PSGetConstantBuffers1(0, kCbSlots, ps_stage_.cbs, ps_stage_.cb_first, ps_stage_.cb_count);
        context_->CSGetConstantBuffers1(0, kCbSlots, cs_stage_.cbs, cs_stage_.cb_first, cs_stage_.cb_count);
        context_->CSGetUnorderedAccessViews(0, kUavSlots, cs_uavs_);
        context_->SOGetTargets(kSoSlots, so_targets_);
        context_->OMGetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs_, &dsv_);
        context_->RSGetViewports(&viewport_count_, viewports_);
        context_->RSGetScissorRects(&scissor_count_, scissors_);
        context_->OMGetBlendState(&blend_, blend_factor_, &sample_mask_);
        context_->OMGetDepthStencilState(&depth_stencil_, &stencil_ref_);
        context_->RSGetState(&rasterizer_);

        context_->GSSetShader(nullptr, nullptr, 0);
        context_->HSSetShader(nullptr, nullptr, 0);
        context_->DSSetShader(nullptr, nullptr, 0);
        context_->SOSetTargets(0, nullptr, nullptr);
    }

    StateGuard::~StateGuard()
    {
        context_->IASetInputLayout(input_layout_);
        context_->IASetPrimitiveTopology(topology_);
        context_->VSSetShader(vs_.shader, vs_.instances, vs_.count);
        context_->PSSetShader(ps_.shader, ps_.instances, ps_.count);
        context_->GSSetShader(gs_.shader, gs_.instances, gs_.count);
        context_->HSSetShader(hs_.shader, hs_.instances, hs_.count);
        context_->DSSetShader(ds_.shader, ds_.instances, ds_.count);
        context_->CSSetShader(cs_.shader, cs_.instances, cs_.count);
        context_->VSSetShaderResources(0, kSrvSlots, vs_stage_.srvs);
        context_->PSSetShaderResources(0, kSrvSlots, ps_stage_.srvs);
        context_->CSSetShaderResources(0, kSrvSlots, cs_stage_.srvs);
        context_->VSSetSamplers(0, kSamplerSlots, vs_stage_.samplers);
        context_->PSSetSamplers(0, kSamplerSlots, ps_stage_.samplers);
        context_->CSSetSamplers(0, kSamplerSlots, cs_stage_.samplers);
        context_->VSSetConstantBuffers1(0, kCbSlots, vs_stage_.cbs, vs_stage_.cb_first, vs_stage_.cb_count);
        context_->PSSetConstantBuffers1(0, kCbSlots, ps_stage_.cbs, ps_stage_.cb_first, ps_stage_.cb_count);
        context_->CSSetConstantBuffers1(0, kCbSlots, cs_stage_.cbs, cs_stage_.cb_first, cs_stage_.cb_count);
        // -1 keeps each UAV counter and each stream-output offset where it was.
        const UINT keep_counts[kUavSlots] = { ~0u, ~0u };
        context_->CSSetUnorderedAccessViews(0, kUavSlots, cs_uavs_, keep_counts);
        const UINT append[kSoSlots] = { ~0u, ~0u, ~0u, ~0u };
        context_->SOSetTargets(kSoSlots, so_targets_, append);
        context_->OMSetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs_, dsv_);
        context_->RSSetViewports(viewport_count_, viewports_);
        context_->RSSetScissorRects(scissor_count_, scissors_);
        context_->OMSetBlendState(blend_, blend_factor_, sample_mask_);
        context_->OMSetDepthStencilState(depth_stencil_, stencil_ref_);
        context_->RSSetState(rasterizer_);

        ID3D11RenderTargetView *rtv = nullptr;
        ID3D11DepthStencilView *dsv = nullptr;
        ID3D11PixelShader *ps = nullptr;
        context_->OMGetRenderTargets(1, &rtv, &dsv);
        context_->PSGetShader(&ps, nullptr, nullptr);
        if (rtv != tripwire_rtv_)
            moved_ = "render target 0";
        else if (dsv != tripwire_dsv_)
            moved_ = "depth-stencil view";
        else if (ps != tripwire_ps_)
            moved_ = "pixel shader";
        release(rtv);
        release(dsv);
        release(ps);

        release(tripwire_rtv_);
        release(tripwire_dsv_);
        release(tripwire_ps_);
        release(input_layout_);
        for (auto *bound : { &vs_.instances, &ps_.instances, &gs_.instances, &hs_.instances, &ds_.instances, &cs_.instances })
            release(*bound);
        release(vs_.shader);
        release(ps_.shader);
        release(gs_.shader);
        release(hs_.shader);
        release(ds_.shader);
        release(cs_.shader);
        for (Stage *stage : { &vs_stage_, &ps_stage_, &cs_stage_ })
        {
            release(stage->srvs);
            release(stage->samplers);
            release(stage->cbs);
        }
        release(cs_uavs_);
        release(so_targets_);
        release(rtvs_);
        release(dsv_);
        release(blend_);
        release(depth_stencil_);
        release(rasterizer_);
    }

    bool Mirror::sync(ID3D11Device *device, ID3D11Resource *like, DXGI_FORMAT view_format, bool render_target)
    {
        ComPtr<ID3D11Texture2D> game;
        if (FAILED(like->QueryInterface(IID_PPV_ARGS(game.GetAddressOf()))))
            return false;
        D3D11_TEXTURE2D_DESC desc;
        game->GetDesc(&desc);
        if (desc.SampleDesc.Count != 1 || desc.ArraySize != 1)
            return false;
        desc.Format = typeless(desc.Format);
        desc.Usage = D3D11_USAGE_DEFAULT;
        desc.BindFlags = D3D11_BIND_SHADER_RESOURCE | (render_target ? D3D11_BIND_RENDER_TARGET : 0);
        desc.CPUAccessFlags = 0;
        desc.MiscFlags = 0;
        if (texture_ && view_format == view_format_ && std::memcmp(&desc, &desc_, sizeof desc) == 0)
            return true;

        *this = Mirror {};
        if (FAILED(device->CreateTexture2D(&desc, nullptr, &texture_)))
            return false;
        D3D11_SHADER_RESOURCE_VIEW_DESC srv = {};
        srv.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
        srv.Texture2D.MipLevels = 1;
        if (is_depth(view_format))
        {
            srv.Format = DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;
            if (FAILED(device->CreateShaderResourceView(texture_.Get(), &srv, &srv_)))
                return *this = Mirror {}, false;
            srv.Format = DXGI_FORMAT_X32_TYPELESS_G8X24_UINT;
            if (FAILED(device->CreateShaderResourceView(texture_.Get(), &srv, &stencil_srv_)))
                return *this = Mirror {}, false;
        }
        else
        {
            srv.Format = linear(view_format);
            if (FAILED(device->CreateShaderResourceView(texture_.Get(), &srv, &srv_)))
                return *this = Mirror {}, false;
            D3D11_RENDER_TARGET_VIEW_DESC rtv = {};
            rtv.Format = srv.Format;
            rtv.ViewDimension = D3D11_RTV_DIMENSION_TEXTURE2D;
            if (render_target && FAILED(device->CreateRenderTargetView(texture_.Get(), &rtv, &rtv_)))
                return *this = Mirror {}, false;
        }
        desc_ = desc;
        view_format_ = view_format;
        return true;
    }

    bool Gpu::init(ID3D11Device *device, ID3D11DeviceContext *context)
    {
        ComPtr<ID3D11DeviceContext1> context1;
        if (FAILED(context->QueryInterface(IID_PPV_ARGS(context1.GetAddressOf()))))
            return false;

        D3D11_SAMPLER_DESC sampler = {};
        sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT;
        sampler.AddressU = sampler.AddressV = sampler.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampler.MaxLOD = D3D11_FLOAT32_MAX;
        D3D11_SAMPLER_DESC linear_sampler = sampler;
        linear_sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;

        D3D11_BUFFER_DESC buffer = {};
        buffer.ByteWidth = sizeof(Constants);
        buffer.Usage = D3D11_USAGE_DYNAMIC;
        buffer.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        buffer.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;

        D3D11_BLEND_DESC blend = {};
        blend.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
        D3D11_DEPTH_STENCIL_DESC depth = {};
        D3D11_RASTERIZER_DESC rasterizer = {};
        rasterizer.FillMode = D3D11_FILL_SOLID;
        rasterizer.CullMode = D3D11_CULL_NONE;
        rasterizer.DepthClipEnable = TRUE;

        Gpu made;
        const bool ok = SUCCEEDED(device->CreateVertexShader(kFullscreenVs, sizeof kFullscreenVs, nullptr, &made.fullscreen_vs_))
            && SUCCEEDED(device->CreatePixelShader(kAmbientPs, sizeof kAmbientPs, nullptr, &made.ambient_ps_))
            && SUCCEEDED(device->CreatePixelShader(kViewPs, sizeof kViewPs, nullptr, &made.view_ps_))
            && SUCCEEDED(device->CreateSamplerState(&sampler, &made.point_))
            && SUCCEEDED(device->CreateSamplerState(&linear_sampler, &made.linear_))
            && SUCCEEDED(device->CreateBuffer(&buffer, nullptr, &made.constants_))
            && SUCCEEDED(device->CreateBlendState(&blend, &made.opaque_))
            && SUCCEEDED(device->CreateDepthStencilState(&depth, &made.no_depth_))
            && SUCCEEDED(device->CreateRasterizerState(&rasterizer, &made.no_cull_));
        if (!ok)
            return false;
        made.device_ = device;
        made.context_ = context1;
        *this = std::move(made);
        return true;
    }

    void Gpu::upload(const Constants &constants)
    {
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (FAILED(context_->Map(constants_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
            return;
        std::memcpy(mapped.pData, &constants, sizeof constants);
        context_->Unmap(constants_.Get(), 0);
    }

    void Gpu::draw_fullscreen(ID3D11PixelShader *shader, ID3D11ShaderResourceView *const *srvs, UINT srv_count, ID3D11RenderTargetView *target, Size size)
    {
        ID3D11DeviceContext1 *c = context_.Get();
        ID3D11SamplerState *const samplers[kSamplerSlots] = { point_.Get(), linear_.Get() };
        ID3D11Buffer *const buffers[1] = { constants_.Get() };
        const D3D11_VIEWPORT viewport = { 0, 0, static_cast<float>(size.width), static_cast<float>(size.height), 0, 1 };
        c->IASetInputLayout(nullptr);
        c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        c->VSSetShader(fullscreen_vs_.Get(), nullptr, 0);
        c->PSSetShader(shader, nullptr, 0);
        c->PSSetConstantBuffers(0, 1, buffers);
        c->PSSetSamplers(0, kSamplerSlots, samplers);
        c->OMSetRenderTargets(1, &target, nullptr);
        c->PSSetShaderResources(0, srv_count, srvs);
        c->RSSetViewports(1, &viewport);
        c->RSSetState(no_cull_.Get());
        c->OMSetBlendState(opaque_.Get(), nullptr, 0xFFFFFFFF);
        c->OMSetDepthStencilState(no_depth_.Get(), 0);
        c->Draw(3, 0);
    }

    std::optional<GameCall> Gpu::run_ambient(const FrameMap &map, const AmbientSettings &settings, const Camera &camera, bool flip)
    {
        const Texture &irradiance = *map[Entry::ambient_diffuse], &normals = *map[Entry::normals], &depth = *map[Entry::depth];
        ID3D11Device *d = device_.Get();
        const auto irradiance_format = static_cast<DXGI_FORMAT>(irradiance.format);
        if (!irradiance_in_.sync(d, native(irradiance), irradiance_format, false) || !irradiance_out_.sync(d, native(irradiance), irradiance_format, true)
            || !normals_.sync(d, native(normals), static_cast<DXGI_FORMAT>(normals.format), false)
            || !depth_.sync(d, native(depth), static_cast<DXGI_FORMAT>(depth.format), false))
            return std::nullopt;

        Constants constants = {};
        std::memcpy(constants.world_to_view, camera.world_to_view, sizeof constants.world_to_view);
        if (!invert(camera.view_to_clip, constants.clip_to_view))
            return std::nullopt;
        const Size size = irradiance_out_.size();
        constants.render_size[0] = static_cast<float>(size.width);
        constants.render_size[1] = static_cast<float>(size.height);
        constants.render_size[2] = 1.0f / size.width;
        constants.render_size[3] = 1.0f / size.height;
        constants.level = settings.level;
        constants.ao_strength = settings.ao_strength;
        constants.ao_radius = settings.ao_radius;
        constants.flip = flip ? 1.0f : 0.0f;
        constants.projection_scale = 0.5f * size.height * camera.view_to_clip[5];
        upload(constants);

        ID3D11DeviceContext1 *c = context_.Get();
        irradiance_in_.copy_from(c, native(irradiance));
        normals_.copy_from(c, native(normals));
        depth_.copy_from(c, native(depth));
        ID3D11ShaderResourceView *const srvs[] = { irradiance_in_.srv(), normals_.srv(), depth_.srv(), depth_.stencil_srv() };
        draw_fullscreen(ambient_ps_.Get(), srvs, 4, irradiance_out_.rtv(), size);
        irradiance_out_.copy_to(c, native(irradiance));
        return GameCall::keep;
    }

    void Gpu::end_frame(View next_view)
    {
        std::swap(pending_, shown_);
        pending_.view = next_view;
        pending_.found = false;
    }

    bool Gpu::snapshot(const Texture &entry)
    {
        if (!pending_.image.sync(device_.Get(), native(entry), static_cast<DXGI_FORMAT>(entry.format), false))
            return false;
        pending_.image.copy_from(context_.Get(), native(entry));
        pending_.found = true;
        return true;
    }

    const char *Gpu::composite(ID3D11Resource *back_buffer, bool flip)
    {
        const char *moved = nullptr;
        if (shown_.view == View::off)
            return moved;
        ComPtr<ID3D11Texture2D> texture;
        if (FAILED(back_buffer->QueryInterface(IID_PPV_ARGS(texture.GetAddressOf()))))
            return moved;
        D3D11_TEXTURE2D_DESC desc;
        texture->GetDesc(&desc);
        if (!back_buffer_.sync(device_.Get(), back_buffer, desc.Format, true))
            return moved;

        Constants constants = {};
        constants.flip = flip ? 1.0f : 0.0f;
        constants.decode = static_cast<uint32_t>(shown_.found ? kViews[static_cast<size_t>(shown_.view)].decode : Decode::missing);
        upload(constants);
        {
            StateGuard guard(context_.Get(), moved);
            ID3D11ShaderResourceView *const srvs[] = { shown_.found ? shown_.image.srv() : nullptr, shown_.found ? shown_.image.stencil_srv() : nullptr };
            draw_fullscreen(view_ps_.Get(), srvs, 2, back_buffer_.rtv(), back_buffer_.size());
        }
        back_buffer_.copy_to(context_.Get(), back_buffer);
        return moved;
    }
}
